import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'

// const inter = Poppins({ subsets: ['latin'], weights: ['100', '200', '300', '400'] })

export const metadata: Metadata = {
  title: 'Avisa',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className="">{children}</body>
    </html>
  )
}
